name: NON-PROD Pipeline

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Please enter SHA code"
        required: true
        type: string

      environment:
        description: "Please select environment"
        required: true
        type: choice
        default: uat
        options:
          - qa
          - uat
          - sit

concurrency:
  group: roboshop-shipping-nonprod
  cancel-in-progress: false

permissions:
  contents: read
  statuses: write
  security-events: read

jobs:
  non-prod-pipeline:
    uses: rajasekharburri-git-actions/workflows/.github/workflows/non-prod-pipeline.yaml@main

    with:
      component: shipping
      version: ${{ inputs.version }}
      environment: ${{ inputs.environment }}

    secrets: inherit